#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n tilleggsstonader get secret azuread-tilleggsstonader-sak-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: tilleggsstonader-sak-lokal
  namespace: tilleggsstonader
  labels:
    team: tilleggsstonader
spec:
  preAuthorizedApplications:
    - application: tilleggsstonader-sak-frontend-lokal
      cluster: dev-gcp
      namespace: tilleggsstonader
  secretName: azuread-tilleggsstonader-sak-lokal
  claims:
    extra:
      - "NAVident"
      - "azp_name"
    groups:
      - id: "0f841c83-0d64-407c-80d5-4eb51dfaee1e" # 0000-GA-Tilleggsstonader-Veileder
      - id: "c1e9edec-0c10-4df2-8c74-324ab9922220" # 0000-GA-Tilleggsstonader-Saksbehandler
      - id: "224b5097-d0af-462c-8d8e-49c0e8a42661" # 0000-GA-Tilleggsstonader-Beslutter
      - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
      - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
      - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte